[project]
name = "core-guard"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.core_guard]
path = "contracts/core_guard.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
